services:
  imap-webhook:
    image: w0ng22/imap-webhook:latest
    container_name: imap-webhook
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data:/data
